import os
import torch
import gradio as gr
import numpy as np
import cv2
import uuid
import zipfile
import subprocess
import sys
import json
from typing import Any, Optional, List, Tuple
from PIL import Image
from gradio_image_prompter import ImagePrompter

try:
    from .runtime_config import gradio_server_name
    from .scene_config import SceneConfigError, load_scene_config
except ImportError:
    from runtime_config import gradio_server_name
    from scene_config import SceneConfigError, load_scene_config

# Grounding SAM imports.
from grounding_sam import detect, plot_segmentation, prepare_model, segment

# Super-resolution module.
try:
    from hypir_wrapper import HYPIRWrapper

    HYPIR_AVAILABLE = True
except ImportError as error:
    print(f"Warning: HYPIR import failed. Super-resolution disabled: {error}")
    HYPIR_AVAILABLE = False


PROMPT_CANVAS_JS = """
() => {
    const stylePromptCanvas = () => {
        document.querySelectorAll("#sam-image-prompter canvas").forEach((canvas) => {
            const context = canvas.getContext("2d");
            if (!context) return;
            context.strokeStyle = "#FFD400";
            context.lineWidth = 3;
            context.shadowColor = "rgba(0, 0, 0, 1)";
            context.shadowBlur = 2;
        });
    };

    const observer = new MutationObserver(stylePromptCanvas);
    observer.observe(document.body, { childList: true, subtree: true });
    stylePromptCanvas();
    window.setInterval(stylePromptCanvas, 250);
}
"""

# Hardware settings.
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
OUTPUT_DIR = "outputs"  # Output directory.
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Loading Segmentation Models on {DEVICE}...")

# 1. model preparation (Grounding SAM)
object_detector, sam_processor, sam_segmentator = prepare_model(
    device=DEVICE,
    detector_id="IDEA-Research/grounding-dino-tiny",
    segmenter_id="facebook/sam2-hiera-large",
)

# 2. model preparation (HYPIR Super-Res)
hypir_model = None
if HYPIR_AVAILABLE:
    config_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "HYPIR",
        "configs",
        "sd2_gradio.yaml",
    )
    if os.path.exists(config_path):
        print(f"Loading HYPIR Enhancer from {config_path}...")
        try:
            hypir_model = HYPIRWrapper(config_path=config_path, device=DEVICE)
        except Exception as e:
            print(f"HYPIR DISABLED: initialization failed: {type(e).__name__}: {e}")
            hypir_model = None
    else:
        print(f"Warning: Config {config_path} not found. HYPIR disabled.")

print("All Models Loaded.")


def zip_debug_outputs(input_dir: str) -> str | None:
    """Package debug artifacts generated by scene_script into input_dir/debug_outputs.zip."""
    debug_dir = os.path.join(input_dir, "debug")
    if not os.path.isdir(debug_dir):
        return None

    zip_path = os.path.join(input_dir, "debug_outputs.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _, files in os.walk(debug_dir):
            for filename in files:
                file_path = os.path.join(root, filename)
                arcname = os.path.relpath(file_path, input_dir)
                zf.write(file_path, arcname)
    return zip_path if os.path.exists(zip_path) else None


def run_external_scene_script(input_dir: str, debug_outputs: bool = False):
    """
    Run the external scene script and return its two output videos.
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    script_path = os.path.join(current_dir, "scene_script.py")
    
    if not os.path.exists(script_path):
        print(f"Error: Script not found at {script_path}")
        return None, None, None
    
    cmd = [
        sys.executable, script_path,
        "--input_dir", input_dir,
    ]
    if debug_outputs:
        cmd.append("--debug")
    
    print(f"Executing command: {' '.join(cmd)}")
    
    # Configure relative imports.
    env = os.environ.copy()
    project_root = os.path.dirname(current_dir) # Parent directory.
    # An absolute project root can also be used.
    env["PYTHONPATH"] = project_root + os.pathsep + env.get("PYTHONPATH", "")

    try:
        subprocess.run(cmd, check=True, text=True, capture_output=True, env=env)
        
        trellis_path = os.path.join(input_dir, "result_trellis.mp4")
        hive_path = os.path.join(input_dir, "result_hive3d.mp4")
        
        res_trellis = trellis_path if os.path.exists(trellis_path) else None
        res_hive = hive_path if os.path.exists(hive_path) else None
        debug_zip = zip_debug_outputs(input_dir) if debug_outputs else None
        
        return res_trellis, res_hive, debug_zip
            
    except subprocess.CalledProcessError as e:
        print(f"❌ Script failed (exit code {e.returncode})")
        print("\n" + "="*20 + " STDERR " + "="*20)
        print(e.stderr) 
        print("="*60 + "\n")
        if e.stdout:
            print("="*20 + " STDOUT " + "="*20)
            print(e.stdout)
            print("="*60)
        return None, None, None
    

def center_and_resize_image(pil_image: Image.Image, target_size: int = 518, canvas_ratio: float = 1.3) -> Image.Image:
    if pil_image.mode != "RGBA":
        pil_image = pil_image.convert("RGBA")

    bbox = pil_image.getbbox()
    if bbox is None:
        return Image.new("RGB", (target_size, target_size), (0, 0, 0))
    
    cropped_image = pil_image.crop(bbox)
    w, h = cropped_image.size
    max_side = max(w, h)
    
    desired_max_side = target_size / canvas_ratio
    scale = desired_max_side / max_side
    
    new_w = int(w * scale)
    new_h = int(h * scale)
    
    resized_image = cropped_image.resize((new_w, new_h), resample=Image.Resampling.LANCZOS)
    final_image = Image.new("RGB", (target_size, target_size), (0, 0, 0))
    
    paste_x = (target_size - new_w) // 2
    paste_y = (target_size - new_h) // 2
    
    final_image.paste(resized_image, (paste_x, paste_y), mask=resized_image)
    return final_image


def split_image_prompts(image_prompts: Any):
    boxes = []
    point_prompts = []
    for prompt in image_prompts.get("points", []):
        if len(prompt) < 6:
            continue
        prompt_type = int(prompt[5])
        if prompt_type == 3:
            x1, y1, x2, y2 = int(prompt[0]), int(prompt[1]), int(prompt[3]), int(prompt[4])
            boxes.append([min(x1, x2), min(y1, y2), max(x1, x2), max(y1, y2)])
        elif prompt_type == 4:
            point_label = int(prompt[2])
            point_prompts.append(
                {"x": int(prompt[0]), "y": int(prompt[1]), "label": point_label}
            )
    return boxes, point_prompts


def point_in_box(point: dict, box: List[int]) -> bool:
    x1, y1, x2, y2 = box
    return x1 <= point["x"] <= x2 and y1 <= point["y"] <= y2


def box_area(box: List[int]) -> int:
    x1, y1, x2, y2 = box
    return max(0, x2 - x1) * max(0, y2 - y1)


def build_prompt_objects(boxes: List[List[int]], point_prompts: List[dict]):
    objects = [{"box": box, "points": []} for box in boxes]
    unassigned_points = []

    for point in point_prompts:
        containing_indices = [
            idx for idx, obj in enumerate(objects) if point_in_box(point, obj["box"])
        ]
        if containing_indices:
            best_idx = min(containing_indices, key=lambda idx: box_area(objects[idx]["box"]))
            objects[best_idx]["points"].append(point)
        else:
            unassigned_points.append(point)

    if not objects and unassigned_points:
        objects.append({"box": None, "points": unassigned_points})
    else:
        for point in unassigned_points:
            objects.append({"box": None, "points": [point]})

    return objects


def build_sam_point_inputs(
    point_prompts: Optional[List[dict]],
) -> Tuple[Optional[List[List[List[float]]]], Optional[List[List[int]]]]:
    if not point_prompts:
        return None, None

    points = [[float(point["x"]), float(point["y"])] for point in point_prompts]
    labels = [int(point["label"]) for point in point_prompts]
    return [[points]], [[labels]]


def clear_prompts(image_prompts: Any):
    if not image_prompts:
        return image_prompts
    image_prompts = dict(image_prompts)
    image_prompts["points"] = []
    return image_prompts

def save_individual_results(
    rgb_image: Image.Image, 
    detections: List[Any], 
    enable_sr: bool = False, 
    sr_prompt: str = "",
    sr_scale: float = 1.0,
    enable_centering: bool = False,
    json_file: Optional[str] = None
) -> Tuple[List[Image.Image], str, str]:
    if not detections:
        return [], None, None
    
    if isinstance(detections, list) and len(detections) > 0 and isinstance(detections[0], list):
        detections = detections[0]
    if not isinstance(detections, list):
         detections = [detections]

    if any(getattr(detection, "mask", None) is None for detection in detections):
        raise gr.Error("Segmentation returned an object without a mask.")

    run_id = str(uuid.uuid4())[:8]
    save_path = os.path.join(OUTPUT_DIR, run_id)
    os.makedirs(save_path, exist_ok=True)
    
    gallery_images = [] 
    file_paths = []     

    # Save scene.png.
    scene_img_path = os.path.join(save_path, "scene.png")
    rgb_image.save(scene_img_path)
    file_paths.append(scene_img_path) 
    print(f"Saved original scene to: {scene_img_path}")  

    # Validate and save config.json.
    config_dest_path = os.path.join(save_path, "config.json")
    labels = [str(i) for i in range(len(detections))]
    if json_file is not None:
        try:
            config_source = getattr(json_file, "name", json_file)
            config = load_scene_config(
                config_source,
                expected_labels=labels,
            )
        except SceneConfigError as error:
            raise gr.Error(str(error)) from error
    else:
        config = {
            "labels": labels,
            "scene_tree": {"scene": labels},
        }

    with open(config_dest_path, "w", encoding="utf-8") as config_file:
        json.dump(config, config_file, indent=2)
    file_paths.append(config_dest_path)
    print(f"Config file saved to: {config_dest_path}")

    original_rgba_np = np.array(rgb_image.convert("RGBA"))
    
    for i, det_result in enumerate(detections):
        mask = det_result.mask
        if mask is None: continue
            
        if isinstance(mask, np.ndarray) and mask.ndim == 2:
            mask = mask[None, ...]
        if mask.ndim == 3:
            mask = mask[0]
            
        mask_uint8 = (mask * 255).astype(np.uint8)
        mask_pil = Image.fromarray(mask_uint8, mode='L')
        
        object_id = i
        mask_filename = os.path.join(save_path, f"{object_id}_mask.png")
        mask_pil.save(mask_filename)
        file_paths.append(mask_filename)

        current_obj_img = original_rgba_np.copy()
        current_obj_img[:, :, 3] = mask_uint8
        cutout_pil = Image.fromarray(current_obj_img)
        was_enhanced = False

        if enable_sr and hypir_model is not None:
            print(f"Enhancing Object {i} with HYPIR (Scale: {sr_scale})...")
            try:
                rgb_content = cutout_pil.convert("RGB")
                alpha_channel = cutout_pil.getchannel("A")

                enhanced_rgb = hypir_model.enhance_image(
                    rgb_content, 
                    prompt=sr_prompt, 
                    upscale=sr_scale,
                    patch_size=512
                )

                if enhanced_rgb is not None:
                    if enhanced_rgb.size != alpha_channel.size:
                        alpha_resized = alpha_channel.resize(enhanced_rgb.size, resample=Image.NEAREST)
                    else:
                        alpha_resized = alpha_channel

                    enhanced_rgba = enhanced_rgb.convert("RGBA")
                    enhanced_rgba.putalpha(alpha_resized)
                    cutout_pil = enhanced_rgba
                    was_enhanced = True
                else:
                    gr.Warning(
                        f"Super-resolution failed for object {i}; "
                        "the original image was retained."
                    )
            except Exception as error:
                gr.Warning(
                    f"Super-resolution failed for object {i}: "
                    f"{type(error).__name__}: {error}"
                )


        if enable_centering:
            cutout_pil = center_and_resize_image(cutout_pil, target_size=518)

        cutout_filename = os.path.join(save_path, f"{object_id}.png")
        cutout_pil.save(cutout_filename)
        file_paths.append(cutout_filename)
        
        label_text = getattr(det_result, 'label', f"Object {object_id}")
        if label_text is None: label_text = f"Object {object_id}"
        
        if was_enhanced:
            label_text += " (Enhanced)"

        gallery_images.append((cutout_filename, label_text))

    if not file_paths:
        return [], None, None
        
    zip_filename = os.path.join(OUTPUT_DIR, f"results_{run_id}.zip")
    with zipfile.ZipFile(zip_filename, 'w') as zipf:
        for file in file_paths:
            zipf.write(file, os.path.basename(file))
            
    return gallery_images, zip_filename, save_path

# Step 1: segment and save inputs.
@torch.no_grad()
def run_segmentation_only(
    image_prompts: Any,
    seg_mode: str,
    text_labels: Optional[str],
    polygon_refinement: bool,
    detect_threshold: float,
    enable_sr: bool,
    sr_prompt: str,
    sr_scale: float,
    enable_centering: bool,
    json_file: Optional[str]
):
    if not image_prompts:
        return None, [], None, None

    if enable_sr and hypir_model is None:
        raise gr.Error(
            "HYPIR is not available because model initialization failed. "
            "Check the server log for 'HYPIR DISABLED'."
        )
    if (
        enable_sr
        and sr_prompt.strip().lower() == "auto"
        and not hypir_model.use_gpt
    ):
        raise gr.Error(
            "The 'auto' enhancement prompt requires GPT_API_KEY, "
            "GPT_BASE_URL, and GPT_MODEL."
        )
        
    rgb_image = image_prompts["image"].convert("RGB")
    boxes, point_prompts = split_image_prompts(image_prompts)

    if seg_mode == "label":
        if not text_labels or len(text_labels.split(",")) == 0:
            gr.Warning("Please enter text labels.")
            return None, [], None, None
        text_labels = text_labels.split(",")
        detections = detect(object_detector, rgb_image, text_labels, detect_threshold)
        print("Running segmentation...")
        detections = segment(
            sam_processor,
            sam_segmentator,
            rgb_image,
            detection_results=detections,
            polygon_refinement=polygon_refinement,
        )
    else:
        if seg_mode in ("box", "box+point") and not boxes:
            gr.Warning("Please draw bounding boxes.")
            return None, [], None, None
        if seg_mode == "point" and not point_prompts:
            gr.Warning("Please click foreground or background points.")
            return None, [], None, None

        prompt_objects = build_prompt_objects(boxes, point_prompts)
        if seg_mode == "box":
            prompt_objects = [obj for obj in prompt_objects if obj["box"] is not None]
        elif seg_mode == "point":
            prompt_objects = [obj for obj in prompt_objects if obj["points"]]

        detections = []
        print(f"Running segmentation for {len(prompt_objects)} object prompt(s)...")
        for idx, obj in enumerate(prompt_objects):
            segment_kwargs = {}
            if obj["box"] is not None:
                segment_kwargs["boxes"] = [[obj["box"]]]
            if seg_mode in ("point", "box+point") and obj["points"]:
                input_points, input_labels = build_sam_point_inputs(obj["points"])
                segment_kwargs["input_points"] = input_points
                segment_kwargs["input_labels"] = input_labels

            obj_detections = segment(
                sam_processor,
                sam_segmentator,
                rgb_image,
                polygon_refinement=polygon_refinement,
                **segment_kwargs,
            )
            for det in obj_detections:
                det.label = f"Object {idx}"
            detections.extend(obj_detections)
    
    seg_map_pil = plot_segmentation(rgb_image, detections)

    # Save results.
    gallery_res, zip_path, current_run_dir = save_individual_results(
        rgb_image, 
        detections, 
        enable_sr=enable_sr, 
        sr_prompt=sr_prompt,
        sr_scale=sr_scale,
        enable_centering=enable_centering,
        json_file=json_file
    )

    torch.cuda.empty_cache()
    
    # Return masks, object gallery, archive, and the task path.
    return seg_map_pil, gallery_res, zip_path, current_run_dir

# Step 2: generate the scene.
def run_scene_generation_step(current_run_dir, debug_outputs):
    """
    Generate a scene from the saved task directory.
    """
    if not current_run_dir or not os.path.exists(current_run_dir):
        gr.Warning("Please run analysis first to generate assets.")
        return None, None, None

    print(f"Starting scene generation in: {current_run_dir}")
    video_trellis, video_hive, debug_zip = run_external_scene_script(current_run_dir, debug_outputs=debug_outputs)
    
    return video_trellis, video_hive, debug_zip


# Gradio interface.
with gr.Blocks(
    title="HIVE-3D Segmentation & Enhancement",
    js=PROMPT_CANVAS_JS,
) as demo:
    gr.Markdown("## HIVE-3D Segmentation & Enhancement Tool")
    
    # Store the current task directory.
    current_run_dir_state = gr.State(value=None)
    
    with gr.Row():
        # Inputs and settings.
        with gr.Column(scale=1):
            image_prompts = ImagePrompter(
                label="Input Image (Drag Boxes, Left-Click FG Points, Right-Click BG Points)",
                type="pil",
                height=640,
                width=640,
                elem_id="sam-image-prompter",
            )
            
            # JSON upload.
            json_input = gr.File(
                label="Upload Config JSON (Optional)", 
                file_types=[".json"],
                file_count="single"
            )

            with gr.Accordion("Segmentation Settings", open=True):
                segmentation_mode = gr.Dropdown(
                    ["box", "point", "box+point", "label"], value="box", label="Mode"
                )
                text_labels = gr.Textbox(label="Text Labels", placeholder="e.g., 'chair, table'")
                clear_points_button = gr.Button("Clear Prompts")
                detect_threshold = gr.Slider(0.1, 0.9, 0.3, label="Detection Threshold")
                polygon_refinement = gr.Checkbox(label="Polygon Refinement", value=False)
            
            with gr.Accordion("Super-Resolution Settings (HYPIR)", open=False):
                enable_sr = gr.Checkbox(
                    label="Enable Super-Resolution on Objects",
                    value=hypir_model is not None,
                    interactive=hypir_model is not None,
                    info=(
                        "HYPIR is ready."
                        if hypir_model is not None
                        else "HYPIR failed to initialize; see the server log."
                    ),
                )
                sr_prompt = gr.Textbox(label="Enhancement Prompt", placeholder="auto", info="Input 'auto' for GPT captioning.")
                sr_scale = gr.Slider(1.0, 4.0, value=2.0, step=0.5, label="Upscale Factor")
                enable_centering = gr.Checkbox(
                    label="Format for Training (Center, Black BG, 518x518)", 
                    value=True,
                    info="If checked, crops opaque area, centers it on black background, and resizes to 518px."
                )
                debug_outputs = gr.Checkbox(
                    label="Enable Debug Outputs",
                    value=False,
                    info="Save intermediate voxels, point clouds, and videos under the current run's debug/ folder."
                )
            
            # Run segmentation.
            seg_button = gr.Button("Run Analysis", variant="primary")

        # Outputs.
        with gr.Column(scale=1):
            gr.Markdown("### 1. Segmentation Results")
            seg_image = gr.Image(label="Combined Map", type="pil", format="png")
            
            gr.Markdown("### 2. Extracted Objects")
            obj_gallery = gr.Gallery(label="Objects", object_fit="contain", height="auto", columns=2)
            
            gr.Markdown("### 3. Download Assets")
            download_file = gr.File(label="Download Results (.zip)")

            gr.Markdown("---")

            gr.Markdown("### 4. ⚔️ Scene Reconstruction Comparison")
            
            # Generate the scene.
            gen_scene_button = gr.Button("Generate Scene", variant="primary")
            
            with gr.Row():
                with gr.Column():
                    gr.Markdown("**Baseline (TRELLIS)**", elem_id="center_text")
                    vid_trellis = gr.Video(label="TRELLIS", autoplay=True, loop=True, height=300)
                
                with gr.Column():
                    gr.Markdown("**Ours (HIVE-3D)**", elem_id="center_text")
                    vid_hive = gr.Video(label="HIVE-3D", autoplay=True, loop=True, height=300)
            debug_download_file = gr.File(label="Download Debug Outputs (.zip)")

    # Event bindings.

    clear_points_button.click(
        clear_prompts,
        inputs=[image_prompts],
        outputs=[image_prompts],
    )

    # Run Analysis: image/settings -> masks, gallery, archive, and task state.
    seg_button.click(
        run_segmentation_only,
        inputs=[
            image_prompts,
            segmentation_mode,
            text_labels,
            polygon_refinement,
            detect_threshold,
            enable_sr,
            sr_prompt,
            sr_scale,
            enable_centering,
            json_input,
        ],
        outputs=[seg_image, obj_gallery, download_file, current_run_dir_state], 
    )

    # Generate Scene: task state -> two videos.
    gen_scene_button.click(
        run_scene_generation_step,
        inputs=[current_run_dir_state, debug_outputs],
        outputs=[vid_trellis, vid_hive, debug_download_file]
    )

# Launch the app.
if __name__ == "__main__":
    demo.launch(server_name=gradio_server_name(os.environ))
